/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#191c1e',
        'on-background': '#191c1e',
        'outline-variant': '#c6c6cd',
        background: '#f7f9fb',
        'secondary-container': '#60f9f2',
        'status-late': '#F5C030',
        'primary-fixed': '#dae2fc',
        'surface-bright': '#f7f9fb',
        secondary: '#006a67',
        'on-surface-variant': '#45474c',
        primary: '#000000',
        'on-primary-container': '#7b849a',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#38dcd5',
        'tertiary-container': '#001d33',
        'primary-container': '#131b2e',
        'surface-container-high': '#e6e8ea',
        'surface-container-lowest': '#ffffff',
        surface: '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'border-subtle': '#1C2E48',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#131b2e',
        'status-onsite': '#38D47A',
        tertiary: '#000000',
        'surface-container': '#eceef0',
        'surface-dim': '#d8dadc',
        'primary-fixed-dim': '#bec6df',
        'on-secondary-container': '#00716d',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'sky-accent': '#E4EEF8',
        'on-primary-fixed-variant': '#3e475b',
        'role-supervisor': '#A888F0',
        'surface-container-highest': '#e0e3e5',
        'on-error-container': '#93000a',
        outline: '#76777d',
        'secondary-fixed': '#60f9f2',
        'surface-tint': '#565e73',
        'on-primary': '#ffffff',
        'inverse-surface': '#2d3133',
        'inverse-primary': '#bec6df',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#00201f',
        'status-absent': '#EF5757',
        'on-secondary-fixed-variant': '#00504d',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 4px 6px -1px rgba(13,22,40,0.08)',
        modal: '0 8px 24px -4px rgba(13,22,40,0.12)',
      },
    },
  },
  plugins: [],
};
